default_context:
  project_name: 'study'
  project_slug: 'study'
  domain_main: 'study.com'
  domain_staging: 'stag.study.com'
  docker_swarm_stack_name_main: 'study-com'
  docker_swarm_stack_name_staging: 'stag-study-com'
  secret_key: '65c0f775b965377ab0704b8f7d4e4c6183e6db7407353454930b1750a647410c'
  first_superuser: 'admin@study.com'
  first_superuser_password: 'eb101c353e9ec10ebdb0fff1'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.study.com", "https://stag.study.com", "https://study.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'mailstudy'
  smtp_user: 'userstudy'
  smtp_password: 'eb101c353e9ec10ebdb0fff1'
  smtp_emails_from_email: 'info@study.com'
  postgres_password: 'eb101c353e9ec10ebdb0fff1'
  pgadmin_default_user: 'admin@study.com'
  pgadmin_default_user_password: 'eb101c353e9ec10ebdb0fff1'
  traefik_constraint_tag: 'study.com'
  traefik_constraint_tag_staging: 'stag.study.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:eb101c353e9ec10ebdb0fff1'
  sentry_dsn: 'https://1234abcd:5678ef@sentry.example.com/30'
  docker_image_prefix: 'std'
  docker_image_backend: 'stdbackend'
  docker_image_celeryworker: 'stdceleryworker'
  docker_image_frontend: 'stdfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
